### ISSUE TITLE
Genetetic Optimization

### ISSUE THREAD

**Issue by sysmaya** [TrevorBlythe/MentisJS#2]
Is there any way to train this network with genetic algorithms?
I like this network for simple tasks that can be implemented in the browser on the client side.
I would like to Generate color palettes.

**Comment by TrevorBlythe** [comment]
I've already made an example for a genetic algorithm in "examples/evolution/evolution.html". (pretty sure this is what you mean) The code is all there. Since the code is a little complicated and I haven't made a better example yet, here are the steps to make a genetic algorithm simply.

1. You need to make a "population", which is basically just a bunch of neural networks that compete. There is already an object in the library for this.
```javascript
let population = new Ment.Population(net_Layers, population_size, elitism, mutation rate, mutation_Intensity)
```
EX:
```javascript
let pop = new Ment.Population([new Ment.FC(3, 3), new Ment.FC(3, 9), new Ment.Sig(9)], 10, 3);
```
The only required parameter is Net Layers and Population Size.

<br><br><br>
2. Rate each Network. Test all the networks and give each of them a score. The highest-scored ones will go on to the next generation. The networks are stored in an array in the population object called "networks"
```javascript
for(var i = 0;i<pop.networks.length;i++){
      let net = pop.networks[i];
      net.score = //However good the network is at making color pallets in your case. 
}
```

<br><br><br>

3. "breed" the best ones. There is an in-built function to do this that does it automatically. The networks will be compared by their score values and the worst ones will be replaced by the best ones with mutations.
```javascript
pop.cullAndBreed();
```
The score values all get automatically set to zero. 


<br><br><br>
4. Repeat
You will probably have to do this hundreds of times with a loop before any good results come in. 

I hope this helps! Sorry for not having a better tutorial or example out yet.
